=== chains-project/bump/schemas/unsuccessful-reproduction-schemas/breaking-update.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/chains-project/breaking-updates/blob/main/schemas/unsuccessful-reproduction-schemas/breaking-update.schema.json",
  "title": "Breaking Update",
  "description": "Data concerning an unreproducible breaking dependency update",
  "type": "object",
  "properties": {
    "url": {
      "description": "The URL of the GitHub pull request introducing the breaking update",
      "type": "string",
      "pattern": "^https://github.com/\\S+/\\S+/pull/\\d+$"
    },
    "project": {
      "description": "The name of the repository containing the breaking update",
      "type": "string"
    },
    "projectOrganisation": {
      "description": "The name of the GitHub organisation containing the breaking update",
      "type": "string"
    },
    "breakingCommit": {
      "description": "The commit hash of the commit introducing the breaking update",
      "type": "string",
      "pattern": "^[0-9a-f]{40}$"
    },
    "prAuthor": {
      "description": "The type of user that introduced the breaking update PR",
      "anyOf": [
        {
          "type": "string",
          "enum": [
            "human",
            "bot",
            "unknown"
          ]
        },
        {
          "type": "null"
        }
      ]
    },
    "preCommitAuthor": {
      "description": "The type of user that introduced the previous commit of the breaking update",
      "anyOf": [
        {
          "type": "string",
          "enum": [
            "human",
            "bot",
            "unknown"
          ]
        },
        {
          "type": "null"
        }
      ]
    },
    "breakingCommitAuthor": {
      "description": "The type of user that introduced the breaking update commit",
      "anyOf": [
        {
          "type": "string",
          "enum": [
            "human",
            "bot",
            "unknown"
          ]
        },
        {
          "type": "null"
        }
      ]
    },
    "updatedDependency": {
      "description": "The updated dependency details",
      "$ref": "breaking-update-dependency.schema.json"
    },
    "javaVersionUsedForReproduction": {
      "description": "The Java version used for the reproduction attempt",
      "type": "string"
    },
    "licenseInfo": {
      "description": "The license information of the updated dependency",
      "type": "string"
    }
  },
  "required": [
    "url",
    "project",
    "projectOrganisation",
    "breakingCommit",
    "prAuthor",
    "preCommitAuthor",
    "breakingCommitAuthor",
    "updatedDependency",
    "javaVersionUsedForReproduction",
    "licenseInfo"
  ]
}

=== chains-project/bump/data/unsuccessful-reproductions/c67872a8d5fe126642b2347bf38e22a1534845e7.json
{
  "url" : "https://github.com/iris-connect/iris-client/pull/602",
  "project" : "iris-client",
  "projectOrganisation" : "iris-connect",
  "breakingCommit" : "c67872a8d5fe126642b2347bf38e22a1534845e7",
  "prAuthor" : "bot",
  "preCommitAuthor" : "human",
  "breakingCommitAuthor" : "bot",
  "updatedDependency" : {
    "dependencyGroupID" : "org.springdoc",
    "dependencyArtifactID" : "springdoc-openapi-ui",
    "previousVersion" : "1.6.5",
    "newVersion" : "1.6.6",
    "dependencyScope" : "compile",
    "versionUpdateType" : "patch"
  },
  "javaVersionUsedForReproduction" : "11",
  "licenseInfo" : "AGPL-3.0"
}

=== chains-project/bump/data/unsuccessful-reproductions/3cb9e27d49e1ed46c0b6511103a0c495e031c362.json
{
  "url" : "https://github.com/aws/aws-encryption-sdk-java/pull/1421",
  "project" : "aws-encryption-sdk-java",
  "projectOrganisation" : "aws",
  "breakingCommit" : "3cb9e27d49e1ed46c0b6511103a0c495e031c362",
  "prAuthor" : "bot",
  "preCommitAuthor" : "bot",
  "breakingCommitAuthor" : "bot",
  "updatedDependency" : {
    "dependencyGroupID" : "com.amazonaws",
    "dependencyArtifactID" : "aws-java-sdk",
    "previousVersion" : "1.12.394",
    "newVersion" : "1.12.417",
    "dependencyScope" : "compile",
    "versionUpdateType" : "patch"
  },
  "javaVersionUsedForReproduction" : "11",
  "licenseInfo" : "Apache-2.0"
}

=== chains-project/bump/data/unsuccessful-reproductions/e143f486fcacef7f5d0602b943ae71b279024856.json
{
  "url" : "https://github.com/sceiler/Java-TestNG-Appium-Selenium/pull/135",
  "project" : "Java-TestNG-Appium-Selenium",
  "projectOrganisation" : "sceiler",
  "breakingCommit" : "e143f486fcacef7f5d0602b943ae71b279024856",
  "prAuthor" : "bot",
  "preCommitAuthor" : "human",
  "breakingCommitAuthor" : "bot",
  "updatedDependency" : {
    "dependencyGroupID" : "io.netty",
    "dependencyArtifactID" : "netty-all",
    "previousVersion" : "4.1.89.Final",
    "newVersion" : "4.1.90.Final",
    "dependencyScope" : "compile",
    "versionUpdateType" : "other"
  },
  "javaVersionUsedForReproduction" : "11",
  "licenseInfo" : "No license found"
}

=== chains-project/bump/data/unsuccessful-reproductions/9875a788f047e1f5cfe29ef55986f1397fa1bd3f.json
{
  "url" : "https://github.com/keycloak/keycloak/pull/11014",
  "project" : "keycloak",
  "projectOrganisation" : "keycloak",
  "breakingCommit" : "9875a788f047e1f5cfe29ef55986f1397fa1bd3f",
  "prAuthor" : "human",
  "preCommitAuthor" : "human",
  "breakingCommitAuthor" : "human",
  "updatedDependency" : {
    "dependencyGroupID" : "org.keycloak",
    "dependencyArtifactID" : "keycloak-admin-ui",
    "previousVersion" : "999-SNAPSHOT",
    "newVersion" : "${project.version}",
    "dependencyScope" : "compile",
    "versionUpdateType" : "other"
  },
  "javaVersionUsedForReproduction" : "11",
  "licenseInfo" : "Apache-2.0"
}

=== chains-project/bump/data/unsuccessful-reproductions/92771cd3dab0f336407b0e6a9ae328880e8cddcd.json
{
  "url" : "https://github.com/gruelbox/transaction-outbox/pull/350",
  "project" : "transaction-outbox",
  "projectOrganisation" : "gruelbox",
  "breakingCommit" : "92771cd3dab0f336407b0e6a9ae328880e8cddcd",
  "prAuthor" : "bot",
  "preCommitAuthor" : "bot",
  "breakingCommitAuthor" : "bot",
  "updatedDependency" : {
    "dependencyGroupID" : "org.jooq",
    "dependencyArtifactID" : "jooq",
    "previousVersion" : "3.16.5",
    "newVersion" : "3.17.5",
    "dependencyScope" : "compile",
    "versionUpdateType" : "minor"
  },
  "javaVersionUsedForReproduction" : "11",
  "licenseInfo" : "Apache-2.0"
}

=== chains-project/bump/data/unsuccessful-reproductions/97309132df571edacc69dda4b9b614385d2122d3.json
{
  "url" : "https://github.com/pinterest/orion/pull/126",
  "project" : "orion",
  "projectOrganisation" : "pinterest",
  "breakingCommit" : "97309132df571edacc69dda4b9b614385d2122d3",
  "prAuthor" : "bot",
  "preCommitAuthor" : "human",
  "breakingCommitAuthor" : "bot",
  "updatedDependency" : {
    "dependencyGroupID" : "com.fasterxml.jackson.core",
    "dependencyArtifactID" : "jackson-databind",
    "previousVersion" : "2.9.10.7",
    "newVersion" : "2.13.4.1",
    "dependencyScope" : "compile",
    "versionUpdateType" : "other"
  },
  "javaVersionUsedForReproduction" : "11",
  "licenseInfo" : "Apache-2.0"
}

=== chains-project/bump/data/unsuccessful-reproductions/1a0429f752cd076ed47dae982851c87fc03acb37.json
{
  "url" : "https://github.com/Jikoo/Regionerator/pull/104",
  "project" : "Regionerator",
  "projectOrganisation" : "Jikoo",
  "breakingCommit" : "1a0429f752cd076ed47dae982851c87fc03acb37",
  "prAuthor" : "bot",
  "preCommitAuthor" : "bot",
  "breakingCommitAuthor" : "bot",
  "updatedDependency" : {
    "dependencyGroupID" : "com.github.elBukkit",
    "dependencyArtifactID" : "PreciousStones",
    "previousVersion" : "1.16.5",
    "newVersion" : "1.17.2",
    "dependencyScope" : "provided",
    "versionUpdateType" : "minor"
  },
  "javaVersionUsedForReproduction" : "11",
  "licenseInfo" : "CC-BY-SA-4.0"
}
