=== chains-project/bump/schemas/not-attempted-reproduction-schemas/breaking-update.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/chains-project/breaking-updates/blob/main/schemas/not-attempted-reproduction-schemas/breaking-update.schema.json",
  "title": "Breaking Update",
  "description": "Data concerning a (potential) breaking dependency update",
  "type": "object",
  "properties": {
    "url": {
      "description": "The URL of the GitHub pull request introducing the breaking update",
      "type": "string",
      "pattern": "^https://github.com/\\S+/\\S+/pull/\\d+$"
    },
    "project": {
      "description": "The name of the repository containing the breaking update",
      "type": "string"
    },
    "breakingCommit": {
      "description": "The commit hash of the commit introducing the breaking update",
      "type": "string",
      "pattern": "^[0-9a-f]{40}$"
    },
    "prAuthor": {
      "description": "The type of user that introduced the breaking update PR",
      "anyOf": [
        {
          "type": "string",
          "enum": [
            "human",
            "bot",
            "unknown"
          ]
        },
        {
          "type": "null"
        }
      ]
    },
    "preCommitAuthor": {
      "description": "The type of user that introduced the previous commit of the breaking update",
      "anyOf": [
        {
          "type": "string",
          "enum": [
            "human",
            "bot",
            "unknown"
          ]
        },
        {
          "type": "null"
        }
      ]
    },
    "breakingCommitAuthor": {
      "description": "The type of user that introduced the breaking update commit",
      "anyOf": [
        {
          "type": "string",
          "enum": [
            "human",
            "bot",
            "unknown"
          ]
        },
        {
          "type": "null"
        }
      ]
    },
    "updatedDependency": {
      "description": "The updated dependency details",
      "$ref": "breaking-update-dependency.schema.json"
    }
  },
  "required": [
    "url",
    "project",
    "breakingCommit",
    "prAuthor",
    "preCommitAuthor",
    "breakingCommitAuthor",
    "updatedDependency"
  ]
}

=== chains-project/bump/data/not-reproduced-data/54e776ddb0ce16f5317a6c2feec640a831b039bb.json
{
  "url": "https://github.com/jcabi/jcabi-github/pull/1603",
  "project": "jcabi-github",
  "breakingCommit": "54e776ddb0ce16f5317a6c2feec640a831b039bb",
  "prAuthor": "bot",
  "preCommitAuthor": "bot",
  "breakingCommitAuthor": "bot",
  "updatedDependency": {
    "dependencyGroupID": "com.jcabi",
    "dependencyArtifactID": "jcabi-xml",
    "previousVersion": "0.27.0",
    "newVersion": "0.27.1",
    "dependencyScope": "compile",
    "versionUpdateType": "patch"
  }
}

=== chains-project/bump/data/not-reproduced-data/0cfac3c0ec4f71ed73a7f88a128e4c3913bee8ec.json
{
  "url" : "https://github.com/querydsl/querydsl/pull/3220",
  "project" : "querydsl",
  "breakingCommit" : "0cfac3c0ec4f71ed73a7f88a128e4c3913bee8ec",
  "prAuthor" : "bot",
  "preCommitAuthor" : "human",
  "breakingCommitAuthor" : "bot",
  "updatedDependency" : {
    "dependencyGroupID" : "com.puppycrawl.tools",
    "dependencyArtifactID" : "checkstyle",
    "previousVersion" : "9.3",
    "newVersion" : "10.1",
    "dependencyScope" : "compile",
    "versionUpdateType" : "major"
  }
}

=== chains-project/bump/data/not-reproduced-data/ffaecf0b1c1bcee783da13ae6d9e52a03f4c9853.json
{
  "url" : "https://github.com/paulcwarren/spring-content/pull/1303",
  "project" : "spring-content",
  "breakingCommit" : "ffaecf0b1c1bcee783da13ae6d9e52a03f4c9853",
  "prAuthor" : "bot",
  "preCommitAuthor" : "human",
  "breakingCommitAuthor" : "bot",
  "updatedDependency" : {
    "dependencyGroupID" : "software.amazon.awssdk",
    "dependencyArtifactID" : "s3",
    "previousVersion" : "2.17.289",
    "newVersion" : "2.20.22",
    "dependencyScope" : "compile",
    "versionUpdateType" : "minor"
  }
}

=== chains-project/bump/data/not-reproduced-data/b25e4a1fffc801f51863affd3a46912839b60b71.json
{
  "url" : "https://github.com/paulcwarren/spring-content-examples/pull/554",
  "project" : "spring-content-examples",
  "breakingCommit" : "b25e4a1fffc801f51863affd3a46912839b60b71",
  "prAuthor" : "bot",
  "preCommitAuthor" : "human",
  "breakingCommitAuthor" : "bot",
  "updatedDependency" : {
    "dependencyGroupID" : "software.amazon.awssdk",
    "dependencyArtifactID" : "netty-nio-client",
    "previousVersion" : "2.17.182",
    "newVersion" : "2.17.242",
    "dependencyScope" : "compile",
    "versionUpdateType" : "patch"
  }
}

=== chains-project/bump/data/not-reproduced-data/8d7dcb490a8c4436889b4a9284006171118f696c.json
{
  "url" : "https://github.com/smallrye/smallrye-stork/pull/454",
  "project" : "smallrye-stork",
  "breakingCommit" : "8d7dcb490a8c4436889b4a9284006171118f696c",
  "prAuthor" : "bot",
  "preCommitAuthor" : "human",
  "breakingCommitAuthor" : "bot",
  "updatedDependency" : {
    "dependencyGroupID" : "org.springframework",
    "dependencyArtifactID" : "spring-framework-bom",
    "previousVersion" : "5.3.24",
    "newVersion" : "6.0.4",
    "dependencyScope" : "import",
    "versionUpdateType" : "major"
  }
}

=== chains-project/bump/data/not-reproduced-data/7023d8f1e9d9d4264acfbbd563c02b456c09c9f2.json
{
  "url" : "https://github.com/ingef/conquery/pull/2646",
  "project" : "conquery",
  "breakingCommit" : "7023d8f1e9d9d4264acfbbd563c02b456c09c9f2",
  "prAuthor" : "bot",
  "preCommitAuthor" : "human",
  "breakingCommitAuthor" : "bot",
  "updatedDependency" : {
    "dependencyGroupID" : "com.github.javaparser",
    "dependencyArtifactID" : "javaparser-symbol-solver-core",
    "previousVersion" : "3.23.1",
    "newVersion" : "3.24.4",
    "dependencyScope" : "compile",
    "versionUpdateType" : "minor"
  }
}

=== chains-project/bump/data/not-reproduced-data/3e574764131a426d47f2891c755bb8c7d1f5be68.json
{
  "url": "https://github.com/javaparser/javaparser/pull/4089",
  "project": "javaparser",
  "breakingCommit": "3e574764131a426d47f2891c755bb8c7d1f5be68",
  "prAuthor": "bot",
  "preCommitAuthor": "human",
  "breakingCommitAuthor": "bot",
  "updatedDependency": {
    "dependencyGroupID": "com.google.guava",
    "dependencyArtifactID": "guava",
    "previousVersion": "32.1.0-jre",
    "newVersion": "32.1.1-jre",
    "dependencyScope": "compile",
    "versionUpdateType": "other"
  }
}

=== chains-project/bump/data/not-reproduced-data/b30d00a13b43d3346518c82cbfaf8b16baed7b1b.json
{
  "url": "https://github.com/googleapis/java-logging-logback/pull/523",
  "project": "java-logging-logback",
  "breakingCommit": "b30d00a13b43d3346518c82cbfaf8b16baed7b1b",
  "prAuthor": "bot",
  "preCommitAuthor": "bot",
  "breakingCommitAuthor": "bot",
  "updatedDependency": {
    "dependencyGroupID": "com.google.cloud",
    "dependencyArtifactID": "libraries-bom",
    "previousVersion": "22.0.0",
    "newVersion": "23.0.0",
    "dependencyScope": "import",
    "versionUpdateType": "major"
  }
}
