=== chains-project/bump/schemas/not-attempted-reproduction-schemas/breaking-update.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/chains-project/breaking-updates/blob/main/schemas/not-attempted-reproduction-schemas/breaking-update.schema.json",
  "title": "Breaking Update",
  "description": "Data concerning a (potential) breaking dependency update",
  "type": "object",
  "properties": {
    "url": {
      "description": "The URL of the GitHub pull request introducing the breaking update",
      "type": "string",
      "pattern": "^https://github.com/\\S+/\\S+/pull/\\d+$"
    },
    "project": {
      "description": "The name of the repository containing the breaking update",
      "type": "string"
    },
    "breakingCommit": {
      "description": "The commit hash of the commit introducing the breaking update",
      "type": "string",
      "pattern": "^[0-9a-f]{40}$"
    },
    "prAuthor": {
      "description": "The type of user that introduced the breaking update PR",
      "anyOf": [
        {
          "type": "string",
          "enum": [
            "human",
            "bot",
            "unknown"
          ]
        },
        {
          "type": "null"
        }
      ]
    },
    "preCommitAuthor": {
      "description": "The type of user that introduced the previous commit of the breaking update",
      "anyOf": [
        {
          "type": "string",
          "enum": [
            "human",
            "bot",
            "unknown"
          ]
        },
        {
          "type": "null"
        }
      ]
    },
    "breakingCommitAuthor": {
      "description": "The type of user that introduced the breaking update commit",
      "anyOf": [
        {
          "type": "string",
          "enum": [
            "human",
            "bot",
            "unknown"
          ]
        },
        {
          "type": "null"
        }
      ]
    },
    "updatedDependency": {
      "description": "The updated dependency details",
      "$ref": "breaking-update-dependency.schema.json"
    }
  },
  "required": [
    "url",
    "project",
    "breakingCommit",
    "prAuthor",
    "preCommitAuthor",
    "breakingCommitAuthor",
    "updatedDependency"
  ]
}

=== chains-project/bump/data/not-reproduced-data/0c5dfb9213f034cda91aca4941bbe218ffcf93fc.json
{
  "url" : "https://github.com/assertj/assertj/pull/2592",
  "project" : "assertj",
  "breakingCommit" : "0c5dfb9213f034cda91aca4941bbe218ffcf93fc",
  "prAuthor" : "bot",
  "preCommitAuthor" : "human",
  "breakingCommitAuthor" : "bot",
  "updatedDependency" : {
    "dependencyGroupID" : "org.jboss.logging",
    "dependencyArtifactID" : "jboss-logging",
    "previousVersion" : "3.4.3.Final",
    "newVersion" : "3.5.0.Final",
    "dependencyScope" : "compile",
    "versionUpdateType" : "other"
  }
}

=== chains-project/bump/data/not-reproduced-data/5a3f3fd7d7b10d5978f17b58569e005946a49e88.json
{
  "url": "https://github.com/jcabi/jcabi-http/pull/383",
  "project": "jcabi-http",
  "breakingCommit": "5a3f3fd7d7b10d5978f17b58569e005946a49e88",
  "prAuthor": "bot",
  "preCommitAuthor": "bot",
  "breakingCommitAuthor": "bot",
  "updatedDependency": {
    "dependencyGroupID": "com.fasterxml.jackson.core",
    "dependencyArtifactID": "jackson-databind",
    "previousVersion": "2.13.4.2",
    "newVersion": "2.14.0",
    "dependencyScope": "provided",
    "versionUpdateType": "other"
  }
}

=== chains-project/bump/data/not-reproduced-data/e75adbd924119f077dae19a2858866528a9702ef.json
{
  "url" : "https://github.com/osgi/osgi.enroute/pull/190",
  "project" : "osgi.enroute",
  "breakingCommit" : "e75adbd924119f077dae19a2858866528a9702ef",
  "prAuthor" : "bot",
  "preCommitAuthor" : "human",
  "breakingCommitAuthor" : "bot",
  "updatedDependency" : {
    "dependencyGroupID" : "ch.qos.logback",
    "dependencyArtifactID" : "logback-core",
    "previousVersion" : "1.2.3",
    "newVersion" : "1.2.9",
    "dependencyScope" : "runtime",
    "versionUpdateType" : "patch"
  }
}

=== chains-project/bump/data/not-reproduced-data/6a96a3c8ab6523e9876ee49fdac32b494cdca4b3.json
{
  "url": "https://github.com/jenkinsci/sloccount-plugin/pull/101",
  "project": "sloccount-plugin",
  "breakingCommit": "6a96a3c8ab6523e9876ee49fdac32b494cdca4b3",
  "prAuthor": "bot",
  "preCommitAuthor": "bot",
  "breakingCommitAuthor": "bot",
  "updatedDependency": {
    "dependencyGroupID": "io.jenkins.tools.bom",
    "dependencyArtifactID": "bom-2.332.x",
    "previousVersion": "1643.v1cffef51df73",
    "newVersion": "1763.v092b_8980a_f5e",
    "dependencyScope": "import",
    "versionUpdateType": "other"
  }
}

=== chains-project/bump/data/not-reproduced-data/3e9f19af03b042bd4759873555910d8e2c737b46.json
{
  "url" : "https://github.com/cmu-db/benchbase/pull/170",
  "project" : "benchbase",
  "breakingCommit" : "3e9f19af03b042bd4759873555910d8e2c737b46",
  "prAuthor" : "bot",
  "preCommitAuthor" : "bot",
  "breakingCommitAuthor" : "bot",
  "updatedDependency" : {
    "dependencyGroupID" : "com.google.cloud",
    "dependencyArtifactID" : "google-cloud-spanner-jdbc",
    "previousVersion" : "2.6.1",
    "newVersion" : "2.7.1",
    "dependencyScope" : "compile",
    "versionUpdateType" : "minor"
  }
}

=== chains-project/bump/data/not-reproduced-data/1d92f77982f7d2adab96e4352f9544e5d8597127.json
{
  "url" : "https://github.com/chocoteam/choco-solver/pull/1020",
  "project" : "choco-solver",
  "breakingCommit" : "1d92f77982f7d2adab96e4352f9544e5d8597127",
  "prAuthor" : "bot",
  "preCommitAuthor" : "human",
  "breakingCommitAuthor" : "bot",
  "updatedDependency" : {
    "dependencyGroupID" : "com.puppycrawl.tools",
    "dependencyArtifactID" : "checkstyle",
    "previousVersion" : "10.6.0",
    "newVersion" : "10.9.1",
    "dependencyScope" : "compile",
    "versionUpdateType" : "minor"
  }
}

=== chains-project/bump/data/not-reproduced-data/da7293058de2eaff9fd9d6b6fc226907d3c615e5.json
{
  "url" : "https://github.com/microsoftgraph/msgraph-sdk-java-core/pull/563",
  "project" : "msgraph-sdk-java-core",
  "breakingCommit" : "da7293058de2eaff9fd9d6b6fc226907d3c615e5",
  "prAuthor" : "bot",
  "preCommitAuthor" : "human",
  "breakingCommitAuthor" : "bot",
  "updatedDependency" : {
    "dependencyGroupID" : "com.azure",
    "dependencyArtifactID" : "azure-core",
    "previousVersion" : "1.29.1",
    "newVersion" : "1.30.0",
    "dependencyScope" : "compile",
    "versionUpdateType" : "minor"
  }
}

=== chains-project/bump/data/not-reproduced-data/bf0f5b998ec7093d8ddd131ea399b4eb5b7767f3.json
{
  "url": "https://github.com/informatici/openhospital-core/pull/422",
  "project": "openhospital-core",
  "breakingCommit": "bf0f5b998ec7093d8ddd131ea399b4eb5b7767f3",
  "prAuthor": "bot",
  "preCommitAuthor": "bot",
  "breakingCommitAuthor": "bot",
  "updatedDependency": {
    "dependencyGroupID": "mysql",
    "dependencyArtifactID": "mysql-connector-java",
    "previousVersion": "5.1.14",
    "newVersion": "8.0.25",
    "dependencyScope": "compile",
    "versionUpdateType": "major"
  }
}
