=== chains-project/bump/schemas/not-attempted-reproduction-schemas/breaking-update.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/chains-project/breaking-updates/blob/main/schemas/not-attempted-reproduction-schemas/breaking-update.schema.json",
  "title": "Breaking Update",
  "description": "Data concerning a (potential) breaking dependency update",
  "type": "object",
  "properties": {
    "url": {
      "description": "The URL of the GitHub pull request introducing the breaking update",
      "type": "string",
      "pattern": "^https://github.com/\\S+/\\S+/pull/\\d+$"
    },
    "project": {
      "description": "The name of the repository containing the breaking update",
      "type": "string"
    },
    "breakingCommit": {
      "description": "The commit hash of the commit introducing the breaking update",
      "type": "string",
      "pattern": "^[0-9a-f]{40}$"
    },
    "prAuthor": {
      "description": "The type of user that introduced the breaking update PR",
      "anyOf": [
        {
          "type": "string",
          "enum": [
            "human",
            "bot",
            "unknown"
          ]
        },
        {
          "type": "null"
        }
      ]
    },
    "preCommitAuthor": {
      "description": "The type of user that introduced the previous commit of the breaking update",
      "anyOf": [
        {
          "type": "string",
          "enum": [
            "human",
            "bot",
            "unknown"
          ]
        },
        {
          "type": "null"
        }
      ]
    },
    "breakingCommitAuthor": {
      "description": "The type of user that introduced the breaking update commit",
      "anyOf": [
        {
          "type": "string",
          "enum": [
            "human",
            "bot",
            "unknown"
          ]
        },
        {
          "type": "null"
        }
      ]
    },
    "updatedDependency": {
      "description": "The updated dependency details",
      "$ref": "breaking-update-dependency.schema.json"
    }
  },
  "required": [
    "url",
    "project",
    "breakingCommit",
    "prAuthor",
    "preCommitAuthor",
    "breakingCommitAuthor",
    "updatedDependency"
  ]
}

=== chains-project/bump/data/not-reproduced-data/9917a52916545aee0ba21958853129037cb7c8c0.json
{
  "url" : "https://github.com/Doclic/NoEncryption/pull/124",
  "project" : "NoEncryption",
  "breakingCommit" : "9917a52916545aee0ba21958853129037cb7c8c0",
  "prAuthor" : "bot",
  "preCommitAuthor" : "human",
  "breakingCommitAuthor" : "bot",
  "updatedDependency" : {
    "dependencyGroupID" : "io.netty",
    "dependencyArtifactID" : "netty-transport",
    "previousVersion" : "4.1.90.Final",
    "newVersion" : "4.1.95.Final",
    "dependencyScope" : "provided",
    "versionUpdateType" : "other"
  }
}

=== chains-project/bump/data/not-reproduced-data/1df0dc6f9f896d413e7ebc2189c9cf9edcf9d9af.json
{
  "url" : "https://github.com/opentripplanner/OpenTripPlanner/pull/4744",
  "project" : "OpenTripPlanner",
  "breakingCommit" : "1df0dc6f9f896d413e7ebc2189c9cf9edcf9d9af",
  "prAuthor" : "bot",
  "preCommitAuthor" : "human",
  "breakingCommitAuthor" : "bot",
  "updatedDependency" : {
    "dependencyGroupID" : "org.processing",
    "dependencyArtifactID" : "core",
    "previousVersion" : "2.2.1",
    "newVersion" : "3.3.7",
    "dependencyScope" : "compile",
    "versionUpdateType" : "major"
  }
}

=== chains-project/bump/data/not-reproduced-data/b9b130a3f02b5785acecebf912b8ece320f1d148.json
{
  "url" : "https://github.com/aws/aws-encryption-sdk-java/pull/1562",
  "project" : "aws-encryption-sdk-java",
  "breakingCommit" : "b9b130a3f02b5785acecebf912b8ece320f1d148",
  "prAuthor" : "bot",
  "preCommitAuthor" : "bot",
  "breakingCommitAuthor" : "bot",
  "updatedDependency" : {
    "dependencyGroupID" : "software.amazon.awssdk",
    "dependencyArtifactID" : "kms",
    "previousVersion" : "2.18.38",
    "newVersion" : "2.20.59",
    "dependencyScope" : "compile",
    "versionUpdateType" : "minor"
  }
}

=== chains-project/bump/data/not-reproduced-data/88ded34e2948daf073b2fdf3d7844ee381512ec4.json
{
  "url" : "https://github.com/matteobaccan/html2pop3/pull/179",
  "project" : "html2pop3",
  "breakingCommit" : "88ded34e2948daf073b2fdf3d7844ee381512ec4",
  "prAuthor" : "bot",
  "preCommitAuthor" : "human",
  "breakingCommitAuthor" : "bot",
  "updatedDependency" : {
    "dependencyGroupID" : "ch.qos.logback",
    "dependencyArtifactID" : "logback-classic",
    "previousVersion" : "1.2.6",
    "newVersion" : "1.2.7",
    "dependencyScope" : "compile",
    "versionUpdateType" : "patch"
  }
}

=== chains-project/bump/data/not-reproduced-data/034bdcd35e34f74c7c486dbe8e359a4d688c2375.json
{
  "url" : "https://github.com/opensrp/opensrp-server-web/pull/850",
  "project" : "opensrp-server-web",
  "breakingCommit" : "034bdcd35e34f74c7c486dbe8e359a4d688c2375",
  "prAuthor" : "bot",
  "preCommitAuthor" : "human",
  "breakingCommitAuthor" : "bot",
  "updatedDependency" : {
    "dependencyGroupID" : "org.hibernate.validator",
    "dependencyArtifactID" : "hibernate-validator",
    "previousVersion" : "6.0.18.Final",
    "newVersion" : "6.0.20.Final",
    "dependencyScope" : "compile",
    "versionUpdateType" : "other"
  }
}
