=== chains-project/bump/schemas/breaking-update.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/chains-project/breaking-updates/blob/main/schemas/breaking-update.schema.json",
  "title": "Breaking Update",
  "description": "Data concerning a (potential) breaking dependency update",
  "type": "object",
  "properties": {
    "url": {
      "description": "The URL of the GitHub pull request introducing the breaking update",
      "type": "string",
      "pattern": "^https://github.com/\\S+/\\S+/pull/\\d+$"
    },
    "project": {
      "description": "The name of the repository containing the breaking update",
      "type": "string"
    },
    "commit": {
      "description": "The commit hash of the commit introducing the breaking update",
      "type": "string",
      "pattern": "^[0-9a-f]{40}$"
    },
    "createdAt": {
      "description": "The date and time when the breaking update pull request was created",
      "type": "string",
      "format": "date-time"
    },
    "dependencyGroupID": {
      "description": "The group ID of the updated dependency",
      "type": "string"
    },
    "dependencyArtifactID": {
      "description": "The artifact ID of the updated dependency",
      "type": "string"
    },
    "previousVersion": {
      "description": "The version of the dependency before the update",
      "type": "string"
    },
    "newVersion": {
      "description": "The version of the dependency after the update",
      "type": "string"
    },
    "versionUpdateType": {
      "description": "The type of change between dependency version, following the SemVer terminology",
      "type": "string",
      "enum": [
        "major",
        "minor",
        "patch",
        "other"
      ]
    },
    "type": {
      "description": "The type of user that introduced the breaking update",
      "type": "string",
      "enum": [
        "human",
        "dependabot",
        "renovate",
        "other"
      ]
    },
    "reproductionStatus": {
      "description": "The current status of the process to reproduce the breaking update locally",
      "type": "string",
      "enum": [
        "not_attempted",
        "successful",
        "unreproducible"
      ]
    },
    "analysis": {
      "description": "The analysis of any local reproduction attempts",
      "anyOf": [
        {
          "$ref": "./breaking-update-analysis.schema.json"
        },
        {
          "type": "null"
        }
      ]
    }
  },
  "required": [
    "url",
    "project",
    "commit",
    "createdAt",
    "dependencyGroupID",
    "dependencyArtifactID",
    "previousVersion",
    "newVersion",
    "versionUpdateType",
    "type",
    "reproductionStatus"
  ]
}

=== chains-project/bump/dataset/0adb9364b8279f40bbb756d1a2c8831de3dca491.json
{
  "url": "https://github.com/zalando/logbook/pull/1262",
  "project": "logbook",
  "commit": "0adb9364b8279f40bbb756d1a2c8831de3dca491",
  "createdAt": "2021-12-29T04:01:01.000+00:00",
  "dependencyGroupID": "org.organicdesign",
  "dependencyArtifactID": "Paguro",
  "previousVersion": "3.1.4",
  "newVersion": "3.8.0",
  "versionUpdateType": "minor",
  "type": "dependabot",
  "reproductionStatus": "unreproducible",
  "analysis": {
    "labels": [
      "PRECEDING_COMMIT_COMPILATION_FAILURE"
    ],
    "javaVersionUsedForReproduction": "11",
    "reproductionLogLocation": "https://github.com/chains-project/breaking-updates/blob/main/reproduction/unreproducible/0adb9364b8279f40bbb756d1a2c8831de3dca491.log"
  }
}

=== chains-project/bump/dataset/ea4cf7e2ef21b3a83963e696cc0d0aafdd6e5464.json
{
  "url": "https://github.com/openrewrite/rewrite-maven-plugin/pull/53",
  "project": "rewrite-maven-plugin",
  "commit": "ea4cf7e2ef21b3a83963e696cc0d0aafdd6e5464",
  "createdAt": "2020-09-21T06:20:38.000+00:00",
  "dependencyGroupID": "org.junit.vintage",
  "dependencyArtifactID": "junit-vintage-engine",
  "previousVersion": "5.6.2",
  "newVersion": "5.7.0",
  "versionUpdateType": "minor",
  "type": "dependabot",
  "reproductionStatus": "not_attempted"
}

=== chains-project/bump/dataset/6d31a6f8bfe73f14b54e6c1ffda0f197e5414c32.json
{
  "url": "https://github.com/Marketcetera/marketcetera/pull/1040",
  "project": "marketcetera",
  "commit": "6d31a6f8bfe73f14b54e6c1ffda0f197e5414c32",
  "createdAt": "2022-11-10T02:23:01.000+00:00",
  "dependencyGroupID": "org.tmatesoft.svnkit",
  "dependencyArtifactID": "svnkit",
  "previousVersion": "1.10.6",
  "newVersion": "1.10.9",
  "versionUpdateType": "patch",
  "type": "dependabot",
  "reproductionStatus": "not_attempted"
}

=== chains-project/bump/dataset/cb84f2dcdfc494a925c664840e58c6275c6a4d9b.json
{
  "url": "https://github.com/paulcwarren/spring-content-examples/pull/523",
  "project": "spring-content-examples",
  "commit": "cb84f2dcdfc494a925c664840e58c6275c6a4d9b",
  "createdAt": "2022-07-05T22:12:05.000+00:00",
  "dependencyGroupID": "software.amazon.awssdk",
  "dependencyArtifactID": "s3",
  "previousVersion": "2.17.182",
  "newVersion": "2.17.225",
  "versionUpdateType": "patch",
  "type": "dependabot",
  "reproductionStatus": "not_attempted"
}

=== chains-project/bump/dataset/3a90b7dfbfa19a07b10bedca54d4fd2dbd51d92d.json
{
  "url": "https://github.com/apache/iotdb/pull/6849",
  "project": "iotdb",
  "commit": "3a90b7dfbfa19a07b10bedca54d4fd2dbd51d92d",
  "createdAt": "2022-08-01T00:15:05.000+00:00",
  "dependencyGroupID": "com.github.ben-manes.caffeine",
  "dependencyArtifactID": "caffeine",
  "previousVersion": "2.9.1",
  "newVersion": "2.9.3",
  "versionUpdateType": "patch",
  "type": "dependabot",
  "reproductionStatus": "unreproducible",
  "analysis": {
    "labels": [
      "PRECEDING_COMMIT_COMPILATION_FAILURE"
    ],
    "javaVersionUsedForReproduction": "11",
    "reproductionLogLocation": "https://github.com/chains-project/breaking-updates/blob/main/reproduction/unreproducible/3a90b7dfbfa19a07b10bedca54d4fd2dbd51d92d.log"
  }
}

=== chains-project/bump/dataset/c11a1e8b5950fe274f126e7b3b529582050814b7.json
{
  "url": "https://github.com/TeamKun/TeamKUNPluginManager/pull/67",
  "project": "TeamKUNPluginManager",
  "commit": "c11a1e8b5950fe274f126e7b3b529582050814b7",
  "createdAt": "2022-01-10T20:09:30.000+00:00",
  "dependencyGroupID": "com.zaxxer",
  "dependencyArtifactID": "HikariCP",
  "previousVersion": "4.0.3",
  "newVersion": "5.0.1",
  "versionUpdateType": "major",
  "type": "dependabot",
  "reproductionStatus": "not_attempted"
}

=== chains-project/bump/dataset/99da0e17f76339c74ead8dc7c3dda55f4b8aaeaf.json
{
  "url": "https://github.com/apache/isis/pull/331",
  "project": "isis",
  "commit": "99da0e17f76339c74ead8dc7c3dda55f4b8aaeaf",
  "createdAt": "2021-01-15T06:20:01.000+00:00",
  "dependencyGroupID": "org.eclipse.persistence",
  "dependencyArtifactID": "org.eclipse.persistence.sdo",
  "previousVersion": "2.7.7",
  "newVersion": "2.7.8",
  "versionUpdateType": "patch",
  "type": "dependabot",
  "reproductionStatus": "not_attempted"
}

=== chains-project/bump/dataset/30657443a9bd90d181871c958a8534a4953f5a2b.json
{
  "url": "https://github.com/googleapis/java-bigquery/pull/2468",
  "project": "java-bigquery",
  "commit": "30657443a9bd90d181871c958a8534a4953f5a2b",
  "createdAt": "2023-01-14T10:22:03.000+00:00",
  "dependencyGroupID": "org.mockito",
  "dependencyArtifactID": "mockito-core",
  "previousVersion": "4.11.0",
  "newVersion": "5.1.0",
  "versionUpdateType": "major",
  "type": "renovate",
  "reproductionStatus": "not_attempted"
}
