=== chains-project/bump/schemas/breaking-update.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/chains-project/breaking-updates/blob/main/schemas/breaking-update.schema.json",
  "title": "Breaking Update",
  "description": "Data concerning a (potential) breaking dependency update",
  "type": "object",
  "properties": {
    "url": {
      "description": "The URL of the GitHub pull request introducing the breaking update",
      "type": "string",
      "pattern": "^https://github.com/\\S+/\\S+/pull/\\d+$"
    },
    "project": {
      "description": "The name of the repository containing the breaking update",
      "type": "string"
    },
    "commit": {
      "description": "The commit hash of the commit introducing the breaking update",
      "type": "string",
      "pattern": "^[0-9a-f]{40}$"
    },
    "createdAt": {
      "description": "The date and time when the breaking update pull request was created",
      "type": "string",
      "format": "date-time"
    },
    "dependencyGroupID": {
      "description": "The group ID of the updated dependency",
      "type": "string"
    },
    "dependencyArtifactID": {
      "description": "The artifact ID of the updated dependency",
      "type": "string"
    },
    "previousVersion": {
      "description": "The version of the dependency before the update",
      "type": "string"
    },
    "newVersion": {
      "description": "The version of the dependency after the update",
      "type": "string"
    },
    "versionUpdateType": {
      "description": "The type of change between dependency version, following the SemVer terminology",
      "type": "string",
      "enum": [
        "major",
        "minor",
        "patch",
        "other"
      ]
    },
    "type": {
      "description": "The type of user that introduced the breaking update",
      "type": "string",
      "enum": [
        "human",
        "dependabot",
        "renovate",
        "other"
      ]
    },
    "reproductionStatus": {
      "description": "The current status of the process to reproduce the breaking update locally",
      "type": "string",
      "enum": [
        "not_attempted",
        "successful",
        "unreproducible"
      ]
    },
    "analysis": {
      "description": "The analysis of any local reproduction attempts",
      "anyOf": [
        {
          "$ref": "./breaking-update-analysis.schema.json"
        },
        {
          "type": "null"
        }
      ]
    }
  },
  "required": [
    "url",
    "project",
    "commit",
    "createdAt",
    "dependencyGroupID",
    "dependencyArtifactID",
    "previousVersion",
    "newVersion",
    "versionUpdateType",
    "type",
    "reproductionStatus"
  ]
}

=== chains-project/bump/dataset/b16fffef3391b0dad11613d5f44934b657e7710d.json
{
  "url": "https://github.com/FluentLenium/FluentLenium/pull/1216",
  "project": "FluentLenium",
  "commit": "b16fffef3391b0dad11613d5f44934b657e7710d",
  "createdAt": "2021-03-10T02:14:26.000+00:00",
  "dependencyGroupID": "net.bytebuddy",
  "dependencyArtifactID": "byte-buddy",
  "previousVersion": "1.10.14",
  "newVersion": "1.10.22",
  "versionUpdateType": "patch",
  "type": "dependabot",
  "reproductionStatus": "not_attempted"
}

=== chains-project/bump/dataset/da616b08bed87397264691470f47638652f0015a.json
{
  "url": "https://github.com/artipie/docker-adapter/pull/514",
  "project": "docker-adapter",
  "commit": "da616b08bed87397264691470f47638652f0015a",
  "createdAt": "2022-05-23T17:12:58.000+00:00",
  "dependencyGroupID": "com.artipie",
  "dependencyArtifactID": "asto",
  "previousVersion": "v1.8.0",
  "newVersion": "v1.12.0",
  "versionUpdateType": "other",
  "type": "dependabot",
  "reproductionStatus": "not_attempted"
}

=== chains-project/bump/dataset/a6baf0d53864c9bf3387ffa85caa24b68ad430d5.json
{
  "url": "https://github.com/oldstuffs/configs/pull/332",
  "project": "configs",
  "commit": "a6baf0d53864c9bf3387ffa85caa24b68ad430d5",
  "createdAt": "2021-05-03T09:17:42.000+00:00",
  "dependencyGroupID": "io.github.portlek",
  "dependencyArtifactID": "replaceable",
  "previousVersion": "2.2.1",
  "newVersion": "2.2.2",
  "versionUpdateType": "patch",
  "type": "dependabot",
  "reproductionStatus": "not_attempted"
}

=== chains-project/bump/dataset/d0461563fdb1ed17801fc4c8fcb96792779db303.json
{
  "url": "https://github.com/quarkusio/quarkus-platform/pull/756",
  "project": "quarkus-platform",
  "commit": "d0461563fdb1ed17801fc4c8fcb96792779db303",
  "createdAt": "2023-01-24T12:59:14.000+00:00",
  "dependencyGroupID": "org.testng",
  "dependencyArtifactID": "testng",
  "previousVersion": "6.14.2",
  "newVersion": "7.7.0",
  "versionUpdateType": "major",
  "type": "dependabot",
  "reproductionStatus": "not_attempted"
}

=== chains-project/bump/dataset/a703497b17e874002d83a349420c7afdd509cde4.json
{
  "url": "https://github.com/Ghost-chu/QuickShop-Hikari/pull/790",
  "project": "QuickShop-Hikari",
  "commit": "a703497b17e874002d83a349420c7afdd509cde4",
  "createdAt": "2023-02-28T19:08:05.000+00:00",
  "dependencyGroupID": "com.palmergames.bukkit.towny",
  "dependencyArtifactID": "towny",
  "previousVersion": "0.98.6.4",
  "newVersion": "0.98.6.9",
  "versionUpdateType": "other",
  "type": "dependabot",
  "reproductionStatus": "not_attempted"
}

=== chains-project/bump/dataset/dd22e7ab7a8b188e07e3567964aeb87d6791284a.json
{
  "url": "https://github.com/knowm/XChange/pull/4261",
  "project": "XChange",
  "commit": "dd22e7ab7a8b188e07e3567964aeb87d6791284a",
  "createdAt": "2021-09-07T12:09:39.000+00:00",
  "dependencyGroupID": "com.github.tomakehurst",
  "dependencyArtifactID": "wiremock-jre8",
  "previousVersion": "2.30.1",
  "newVersion": "2.31.0",
  "versionUpdateType": "minor",
  "type": "dependabot",
  "reproductionStatus": "not_attempted"
}

=== chains-project/bump/dataset/66ce02449f96269ddfa2e92789e3085673209fb7.json
{
  "url": "https://github.com/smallrye/smallrye-graphql/pull/1209",
  "project": "smallrye-graphql",
  "commit": "66ce02449f96269ddfa2e92789e3085673209fb7",
  "createdAt": "2021-12-06T19:12:53.000+00:00",
  "dependencyGroupID": "org.apache.maven.plugin-tools",
  "dependencyArtifactID": "maven-plugin-annotations",
  "previousVersion": "3.6.1",
  "newVersion": "3.6.2",
  "versionUpdateType": "patch",
  "type": "dependabot",
  "reproductionStatus": "unreproducible",
  "analysis": {
    "labels": [
      "PRECEDING_COMMIT_TEST_FAILURE"
    ],
    "javaVersionUsedForReproduction": "11",
    "reproductionLogLocation": "https://github.com/chains-project/breaking-updates/blob/main/reproduction/unreproducible/66ce02449f96269ddfa2e92789e3085673209fb7.log"
  }
}

=== chains-project/bump/dataset/b1db8931a73b949dfa2eb5f453b2ca87608d896c.json
{
  "url": "https://github.com/TAKETODAY/today-infrastructure/pull/93",
  "project": "today-infrastructure",
  "commit": "b1db8931a73b949dfa2eb5f453b2ca87608d896c",
  "createdAt": "2021-12-15T11:09:33.000+00:00",
  "dependencyGroupID": "org.apache.logging.log4j",
  "dependencyArtifactID": "log4j-core",
  "previousVersion": "2.15.0",
  "newVersion": "2.16.0",
  "versionUpdateType": "minor",
  "type": "dependabot",
  "reproductionStatus": "not_attempted"
}
