=== chains-project/bump/schemas/breaking-update.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/chains-project/breaking-updates/blob/main/schemas/breaking-update.schema.json",
  "title": "Breaking Update",
  "description": "Data concerning a (potential) breaking dependency update",
  "type": "object",
  "properties": {
    "url": {
      "description": "The URL of the GitHub pull request introducing the breaking update",
      "type": "string",
      "pattern": "^https://github.com/\\S+/\\S+/pull/\\d+$"
    },
    "project": {
      "description": "The name of the repository containing the breaking update",
      "type": "string"
    },
    "commit": {
      "description": "The commit hash of the commit introducing the breaking update",
      "type": "string",
      "pattern": "^[0-9a-f]{40}$"
    },
    "createdAt": {
      "description": "The date and time when the breaking update pull request was created",
      "type": "string",
      "format": "date-time"
    },
    "dependencyGroupID": {
      "description": "The group ID of the updated dependency",
      "type": "string"
    },
    "dependencyArtifactID": {
      "description": "The artifact ID of the updated dependency",
      "type": "string"
    },
    "previousVersion": {
      "description": "The version of the dependency before the update",
      "type": "string"
    },
    "newVersion": {
      "description": "The version of the dependency after the update",
      "type": "string"
    },
    "versionUpdateType": {
      "description": "The type of change between dependency version, following the SemVer terminology",
      "type": "string",
      "enum": [
        "major",
        "minor",
        "patch",
        "other"
      ]
    },
    "type": {
      "description": "The type of user that introduced the breaking update",
      "type": "string",
      "enum": [
        "human",
        "dependabot",
        "renovate",
        "other"
      ]
    },
    "reproductionStatus": {
      "description": "The current status of the process to reproduce the breaking update locally",
      "type": "string",
      "enum": [
        "not_attempted",
        "successful",
        "unreproducible"
      ]
    },
    "analysis": {
      "description": "The analysis of any local reproduction attempts",
      "anyOf": [
        {
          "$ref": "./breaking-update-analysis.schema.json"
        },
        {
          "type": "null"
        }
      ]
    }
  },
  "required": [
    "url",
    "project",
    "commit",
    "createdAt",
    "dependencyGroupID",
    "dependencyArtifactID",
    "previousVersion",
    "newVersion",
    "versionUpdateType",
    "type",
    "reproductionStatus"
  ]
}

=== chains-project/bump/dataset/038fd5fca85abe629d86ce0b1e316999074ad36b.json
{
  "url": "https://github.com/geotools/geotools/pull/4265",
  "project": "geotools",
  "commit": "038fd5fca85abe629d86ce0b1e316999074ad36b",
  "createdAt": "2023-04-15T15:18:07.000+00:00",
  "dependencyGroupID": "org.json",
  "dependencyArtifactID": "json",
  "previousVersion": "20210307",
  "newVersion": "20230227",
  "versionUpdateType": "other",
  "type": "human",
  "reproductionStatus": "not_attempted"
}

=== chains-project/bump/dataset/683c9e0029129e17c39d554fbf75879ca01d4cbb.json
{
  "url": "https://github.com/liquibase/liquibase-redshift/pull/121",
  "project": "liquibase-redshift",
  "commit": "683c9e0029129e17c39d554fbf75879ca01d4cbb",
  "createdAt": "2023-02-27T22:12:36.000+00:00",
  "dependencyGroupID": "org.yaml",
  "dependencyArtifactID": "snakeyaml",
  "previousVersion": "1.33",
  "newVersion": "2.0",
  "versionUpdateType": "other",
  "type": "dependabot",
  "reproductionStatus": "not_attempted"
}

=== chains-project/bump/dataset/c1e2869d5693048869f5e380566f281be7b69fb2.json
{
  "url": "https://github.com/smoketurner/dropwizard-consul/pull/126",
  "project": "dropwizard-consul",
  "commit": "c1e2869d5693048869f5e380566f281be7b69fb2",
  "createdAt": "2020-11-23T06:09:33.000+00:00",
  "dependencyGroupID": "com.orbitz.consul",
  "dependencyArtifactID": "consul-client",
  "previousVersion": "1.4.2",
  "newVersion": "1.5.0",
  "versionUpdateType": "minor",
  "type": "dependabot",
  "reproductionStatus": "not_attempted"
}

=== chains-project/bump/dataset/3729ebb21e6cb5ca1da1d054f3187b4c4c7dd707.json
{
  "url": "https://github.com/JakeWharton/twirl-maven-plugin/pull/66",
  "project": "twirl-maven-plugin",
  "commit": "3729ebb21e6cb5ca1da1d054f3187b4c4c7dd707",
  "createdAt": "2023-01-02T13:01:26.000+00:00",
  "dependencyGroupID": "org.apache.maven",
  "dependencyArtifactID": "maven-core",
  "previousVersion": "3.6.0",
  "newVersion": "3.8.7",
  "versionUpdateType": "minor",
  "type": "dependabot",
  "reproductionStatus": "not_attempted"
}

=== chains-project/bump/dataset/a82ebf2eb1f2f8922191a70c0f95addd2a948fc6.json
{
  "url": "https://github.com/Pante/chimera/pull/413",
  "project": "chimera",
  "commit": "a82ebf2eb1f2f8922191a70c0f95addd2a948fc6",
  "createdAt": "2022-09-28T21:27:07.000+00:00",
  "dependencyGroupID": "org.apache.commons",
  "dependencyArtifactID": "commons-text",
  "previousVersion": "1.9",
  "newVersion": "1.10.0",
  "versionUpdateType": "other",
  "type": "dependabot",
  "reproductionStatus": "not_attempted"
}

=== chains-project/bump/dataset/8831f5e5dc15a7e5ff1f691fe7a90cbcffbc2cda.json
{
  "url": "https://github.com/Adyen/adyen-java-api-library/pull/785",
  "project": "adyen-java-api-library",
  "commit": "8831f5e5dc15a7e5ff1f691fe7a90cbcffbc2cda",
  "createdAt": "2022-08-13T13:06:17.000+00:00",
  "dependencyGroupID": "org.mockito",
  "dependencyArtifactID": "mockito-core",
  "previousVersion": "4.6.1",
  "newVersion": "4.7.0",
  "versionUpdateType": "minor",
  "type": "renovate",
  "reproductionStatus": "unreproducible",
  "analysis": {
    "labels": [
      "NO_FAILURE"
    ],
    "javaVersionUsedForReproduction": "11",
    "reproductionLogLocation": "https://github.com/chains-project/breaking-updates/blob/main/reproduction/unreproducible/8831f5e5dc15a7e5ff1f691fe7a90cbcffbc2cda.log"
  }
}

=== chains-project/bump/dataset/09b9d23004df07a04d1cdc6a5ae61431c9346f78.json
{
  "url": "https://github.com/paulcwarren/spring-content/pull/1386",
  "project": "spring-content",
  "commit": "09b9d23004df07a04d1cdc6a5ae61431c9346f78",
  "createdAt": "2023-04-26T06:59:46.000+00:00",
  "dependencyGroupID": "software.amazon.awssdk",
  "dependencyArtifactID": "s3",
  "previousVersion": "2.17.289",
  "newVersion": "2.20.53",
  "versionUpdateType": "minor",
  "type": "dependabot",
  "reproductionStatus": "not_attempted"
}

=== chains-project/bump/dataset/63f48f58f46f2e226f66058f1e90aebaf831a0f7.json
{
  "url": "https://github.com/dlsc-software-consulting-gmbh/PreferencesFX/pull/369",
  "project": "PreferencesFX",
  "commit": "63f48f58f46f2e226f66058f1e90aebaf831a0f7",
  "createdAt": "2021-08-25T04:23:06.000+00:00",
  "dependencyGroupID": "org.mockito",
  "dependencyArtifactID": "mockito-core",
  "previousVersion": "3.11.1",
  "newVersion": "3.12.3",
  "versionUpdateType": "minor",
  "type": "dependabot",
  "reproductionStatus": "unreproducible",
  "analysis": {
    "labels": [
      "PRECEDING_COMMIT_COMPILATION_FAILURE"
    ],
    "javaVersionUsedForReproduction": "11",
    "reproductionLogLocation": "https://github.com/chains-project/breaking-updates/blob/main/reproduction/unreproducible/63f48f58f46f2e226f66058f1e90aebaf831a0f7.log"
  }
}
