=== chains-project/bump/schemas/successful-reproduction-schemas/breaking-update.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/chains-project/breaking-updates/blob/main/schemas/successful-reproduction-schemas/breaking-update.schema.json",
  "title": "Breaking Update",
  "description": "Data concerning a successfully reproduced breaking dependency update",
  "type": "object",
  "properties": {
    "url": {
      "description": "The URL of the GitHub pull request introducing the breaking update",
      "type": "string",
      "pattern": "^https://github.com/\\S+/\\S+/pull/\\d+$"
    },
    "project": {
      "description": "The name of the repository containing the breaking update",
      "type": "string"
    },
    "breakingCommit": {
      "description": "The commit hash of the commit introducing the breaking update",
      "type": "string",
      "pattern": "^[0-9a-f]{40}$"
    },
    "prAuthor": {
      "description": "The type of user that introduced the breaking update PR",
      "anyOf": [
        {
          "type": "string",
          "enum": [
            "human",
            "bot",
            "unknown"
          ]
        },
        {
          "type": "null"
        }
      ]
    },
    "preCommitAuthor": {
      "description": "The type of user that introduced the previous commit of the breaking update",
      "anyOf": [
        {
          "type": "string",
          "enum": [
            "human",
            "bot",
            "unknown"
          ]
        },
        {
          "type": "null"
        }
      ]
    },
    "breakingCommitAuthor": {
      "description": "The type of user that introduced the breaking update commit",
      "anyOf": [
        {
          "type": "string",
          "enum": [
            "human",
            "bot",
            "unknown"
          ]
        },
        {
          "type": "null"
        }
      ]
    },
    "updatedDependency": {
      "description": "The updated dependency details",
      "$ref": "breaking-update-dependency.schema.json"
    },
    "preCommitReproductionCommand": {
      "description": "The command to build the project without the breaking update commit",
      "type": "string"
    },
    "breakingUpdateReproductionCommand": {
      "description": "The command to build the project with the breaking update commit",
      "type": "string"
    },
    "javaVersionUsedForReproduction": {
      "description": "The Java version used for the reproduction attempt",
      "type": "string"
    },
    "failureCategory": {
      "description": "The category of the root cause of the reproduction failure",
      "type": "string",
      "enum": [
        "DEPENDENCY_RESOLUTION_FAILURE",
        "MAVEN_ENFORCER_FAILURE",
        "COMPILATION_FAILURE",
        "TEST_FAILURE",
        "UNKNOWN_FAILURE"
      ]
    }
  },
  "required": [
    "url",
    "project",
    "breakingCommit",
    "prAuthor",
    "preCommitAuthor",
    "breakingCommitAuthor",
    "updatedDependency",
    "preCommitReproductionCommand",
    "breakingUpdateReproductionCommand",
    "javaVersionUsedForReproduction",
    "failureCategory"
  ]
}

=== chains-project/bump/data/benchmark/dde0743630a540bff1ba3033b7016fcfc345122f.json
{
  "url" : "https://github.com/dadoonet/fscrawler/pull/1281",
  "project" : "fscrawler",
  "breakingCommit" : "dde0743630a540bff1ba3033b7016fcfc345122f",
  "prAuthor" : "bot",
  "preCommitAuthor" : "human",
  "breakingCommitAuthor" : "bot",
  "updatedDependency" : {
    "dependencyGroupID" : "org.apache.poi",
    "dependencyArtifactID" : "poi-scratchpad",
    "previousVersion" : "4.1.2",
    "newVersion" : "5.0.0",
    "dependencyScope" : "compile",
    "versionUpdateType" : "major",
    "githubCompareLink" : "A GitHub repository could not be found for the updated dependency.",
    "mavenSourceLinkPre" : "https://repo1.maven.org/maven2/org/apache/poi/poi-scratchpad/4.1.2/poi-scratchpad-4.1.2-sources.jar",
    "mavenSourceLinkBreaking" : "https://repo1.maven.org/maven2/org/apache/poi/poi-scratchpad/5.0.0/poi-scratchpad-5.0.0-sources.jar",
    "updatedFileType" : "JAR"
  },
  "preCommitReproductionCommand" : "docker run ghcr.io/chains-project/breaking-updates:dde0743630a540bff1ba3033b7016fcfc345122f-pre",
  "breakingUpdateReproductionCommand" : "docker run ghcr.io/chains-project/breaking-updates:dde0743630a540bff1ba3033b7016fcfc345122f-breaking",
  "javaVersionUsedForReproduction" : "11",
  "failureCategory" : "TEST_FAILURE"
}

=== chains-project/bump/data/benchmark/99a43573c3ea90d8b942627b8ea947933d229863.json
{
  "url" : "https://github.com/jenkinsci/github-oauth-plugin/pull/202",
  "project" : "github-oauth-plugin",
  "breakingCommit" : "99a43573c3ea90d8b942627b8ea947933d229863",
  "prAuthor" : "bot",
  "preCommitAuthor" : "bot",
  "breakingCommitAuthor" : "bot",
  "updatedDependency" : {
    "dependencyGroupID" : "org.jenkins-ci.plugins",
    "dependencyArtifactID" : "github-branch-source",
    "previousVersion" : "2.11.4",
    "newVersion" : "1694.vd46793a_c4a_57",
    "dependencyScope" : "compile",
    "versionUpdateType" : "other",
    "githubCompareLink" : "A GitHub repository could not be found for the updated dependency.",
    "mavenSourceLinkPre" : null,
    "mavenSourceLinkBreaking" : null,
    "updatedFileType" : "JAR"
  },
  "preCommitReproductionCommand" : "docker run ghcr.io/chains-project/breaking-updates:99a43573c3ea90d8b942627b8ea947933d229863-pre",
  "breakingUpdateReproductionCommand" : "docker run ghcr.io/chains-project/breaking-updates:99a43573c3ea90d8b942627b8ea947933d229863-breaking",
  "javaVersionUsedForReproduction" : "11",
  "failureCategory" : "UNKNOWN_FAILURE"
}

=== chains-project/bump/data/benchmark/06c5386831e97e94d9b9fd155d3ea4aa8711c4e7.json
{
  "url" : "https://github.com/jenkinsci/code-coverage-api-plugin/pull/645",
  "project" : "code-coverage-api-plugin",
  "breakingCommit" : "06c5386831e97e94d9b9fd155d3ea4aa8711c4e7",
  "prAuthor" : "bot",
  "preCommitAuthor" : "human",
  "breakingCommitAuthor" : "bot",
  "updatedDependency" : {
    "dependencyGroupID" : "org.jenkins-ci",
    "dependencyArtifactID" : "acceptance-test-harness",
    "previousVersion" : "5504.v485694f31cdf",
    "newVersion" : "5541.va_c0a_36b_b_f825",
    "dependencyScope" : "compile",
    "versionUpdateType" : "other",
    "githubCompareLink" : "A GitHub repository could not be found for the updated dependency.",
    "mavenSourceLinkPre" : null,
    "mavenSourceLinkBreaking" : null,
    "updatedFileType" : "JAR"
  },
  "preCommitReproductionCommand" : "docker run ghcr.io/chains-project/breaking-updates:06c5386831e97e94d9b9fd155d3ea4aa8711c4e7-pre",
  "breakingUpdateReproductionCommand" : "docker run ghcr.io/chains-project/breaking-updates:06c5386831e97e94d9b9fd155d3ea4aa8711c4e7-breaking",
  "javaVersionUsedForReproduction" : "11",
  "failureCategory" : "COMPILATION_FAILURE"
}
